In [28]:
import csv, json, codecs, uuid
import pandas as pd
import numpy as np

In [11]:
datafile = 'Meteorite_Landings.csv'

## cleaning data file

In [89]:
df = pd.read_csv(datafile,  encoding = "ISO-8859-1")
df

,name,id,mass (g),year,reclat,reclong
0,Aachen,1,21.0,01/01/1880 12:00:00 AM,50.77500,6.08333
1,Aarhus,2,720.0,1/1/51 0:00,56.18333,10.23333
2,Abee,6,107000.0,1/1/52 0:00,54.21667,-113.00000
3,Acapulco,10,1914.0,1/1/76 0:00,16.88333,-99.90000
4,Achiras,370,780.0,1/1/02 0:00,-33.16667,-64.95000
5,Adhi Kot,379,4239.0,1/1/19 0:00,32.10000,71.80000
6,Adzhi-Bogdo (stone),390,910.0,1/1/49 0:00,44.83333,95.16667
7,Agen,392,30000.0,01/01/1814 12:00:00 AM,44.21667,0.61667
8,Aguada,398,1620.0,1/1/30 0:00,-31.60000,-65.23333
9,Aguila Blanca,417,1440.0,1/1/20 0:00,-30.86667,-64.55000
10,Aioun el Atrouss,423,1000.0,1/1/74 0:00,16.39806,-9.57028
11,AÌør,424,24000.0,1/1/25 0:00,19.08333,8.38333
12,Aire-sur-la-Lys,425,NaN,01/01/1769 12:00:00 AM,50.66667,2.33333
13,Akaba,426,779.0,1/1/49 0:00,29.51667,35.05000
14,Akbarpur,427,1800.0,01/01/1838 12:00:00 AM,29.71667,77.95000
15,Akwanga,432,3000.0,1/1/59 0:00,8.91667,8.43333
16,Akyumak,433,50000.0,1/1/81 0:00,39.91667,42.81667
17,Al Rais,446,160.0,1/1/57 0:00,24.41667,39.51667
18,Al Zarnkh,447,700.0,1/1/01 0:00,13.66033,28.96000
19,Alais,448,6000.0,01/01/1806 12:00:00 AM,44.11667,4.08333
20,Albareto,453,2000.0,01/01/1766 12:00:00 AM,44.65000,11.01667
21,Alberta,454,625.0,1/1/49 0:00,2.00000,22.66667
22,Alby sur ChÌ©ran,458,252.0,1/1/02 0:00,45.82133,6.01533
23,Aldsworth,461,700.0,01/01/1835 12:00:00 AM,51.78333,-1.78333
24,Aleppo,462,3200.0,01/01/1873 12:00:00 AM,36.23333,37.13333
25,Alessandria,463,908.0,01/01/1860 12:00:00 AM,44.88333,8.75000
26,Alexandrovsky,465,9251.0,1/1/00 0:00,50.95000,31.81667
27,Alfianello,466,228000.0,01/01/1883 12:00:00 AM,45.26667,10.15000
28,Allegan,2276,32000.0,01/01/1899 12:00:00 AM,42.53333,-85.88333
29,Allende,2278,2000000.0,1/1/69 0:00,26.96667,-105.31667
...,...,...,...,...,...,...
45686,Ysleta,30375,140700.0,1/1/14 0:00,31.65000,-106.18333
45687,Yucca 015,57175,3.0,1/1/11 0:00,34.81970,-114.27610
45688,Yucca 016,57158,25.9,1/1/11 0:00,34.82658,-114.27763
45689,Yucca 017,57159,200.0,1/1/11 0:00,34.81923,-114.27735
45690,Yudoma,30376,7600.0,1/1/46 0:00,60.00000,140.00000
45691,Zacatecas (1792),30381,1000000.0,01/01/1792 12:00:00 AM,22.81667,-102.56667
45692,Zacatecas (1969),30382,6660.0,1/1/69 0:00,NaN,NaN
45693,Zaffra,30383,3000.0,1/1/19 0:00,35.00000,-94.75000
45694,Zag (b),30385,300.0,1/1/99 0:00,27.33333,-9.33333
45695,Zagora,30387,50000.0,1/1/87 0:00,30.36667,-5.85000
45696,Zakâodzie,30390,8680.0,1/1/98 0:00,50.76278,22.86611
45697,Zapaliname,30392,85000.0,1/1/98 0:00,25.00944,-100.75000
45698,Zapata County,30393,NaN,1/1/30 0:00,27.00000,-99.00000
45699,ZapotitlÌÁn Salinas,30394,27.7,1/1/84 0:00,18.33333,-97.50000
45700,Zaragoza,48916,162000.0,NaN,41.65000,-0.86667
45701,Zegdou,30398,6700.0,1/1/98 0:00,29.75000,-4.50000
45702,Zelfana,31353,1058.0,1/1/02 0:00,32.15833,4.63333
45703,Zenda,30400,3700.0,1/1/55 0:00,42.51333,-88.48944
45704,Zerga,30402,76.0,1/1/73 0:00,20.25000,-12.68333
45705,Zerhamra,30403,630000.0,1/1/67 0:00,29.85861,-2.64500
45706,Zerkaly,31354,16000.0,1/1/56 0:00,52.13333,81.96667
45707,Zhaoping,54609,2000000.0,1/1/83 0:00,24.23333,111.18333
45708,Zhigansk,30405,900000.0,1/1/66 0:00,68.00000,128.30000
45709,Zhongxiang,30406,100000.0,1/1/81 0:00,31.20000,112.50000
45710,Zillah 001,31355,1475.0,1/1/90 0:00,29.03700,17.01850
45711,Zillah 002,31356,172.0,1/1/90 0:00,29.03700,17.01850
45712,Zinder,30409,46.0,1/1/99 0:00,13.78333,8.96667
45713,Zlin,30410,3.3,1/1/39 0:00,49.25000,17.66667
45714,Zubkovsky,31357,2167.0,1/1/03 0:00,49.78917,41.50460
45715,Zulu Queen,30414,200.0,1/1/76 0:00,33.98333,-115.68333

In [90]:
dropped = df.dropna(axis=0, how='any')
dropped

,name,id,mass (g),year,reclat,reclong
0,Aachen,1,21.0,01/01/1880 12:00:00 AM,50.77500,6.08333
1,Aarhus,2,720.0,1/1/51 0:00,56.18333,10.23333
2,Abee,6,107000.0,1/1/52 0:00,54.21667,-113.00000
3,Acapulco,10,1914.0,1/1/76 0:00,16.88333,-99.90000
4,Achiras,370,780.0,1/1/02 0:00,-33.16667,-64.95000
5,Adhi Kot,379,4239.0,1/1/19 0:00,32.10000,71.80000
6,Adzhi-Bogdo (stone),390,910.0,1/1/49 0:00,44.83333,95.16667
7,Agen,392,30000.0,01/01/1814 12:00:00 AM,44.21667,0.61667
8,Aguada,398,1620.0,1/1/30 0:00,-31.60000,-65.23333
9,Aguila Blanca,417,1440.0,1/1/20 0:00,-30.86667,-64.55000
10,Aioun el Atrouss,423,1000.0,1/1/74 0:00,16.39806,-9.57028
11,AÌør,424,24000.0,1/1/25 0:00,19.08333,8.38333
13,Akaba,426,779.0,1/1/49 0:00,29.51667,35.05000
14,Akbarpur,427,1800.0,01/01/1838 12:00:00 AM,29.71667,77.95000
15,Akwanga,432,3000.0,1/1/59 0:00,8.91667,8.43333
16,Akyumak,433,50000.0,1/1/81 0:00,39.91667,42.81667
17,Al Rais,446,160.0,1/1/57 0:00,24.41667,39.51667
18,Al Zarnkh,447,700.0,1/1/01 0:00,13.66033,28.96000
19,Alais,448,6000.0,01/01/1806 12:00:00 AM,44.11667,4.08333
20,Albareto,453,2000.0,01/01/1766 12:00:00 AM,44.65000,11.01667
21,Alberta,454,625.0,1/1/49 0:00,2.00000,22.66667
22,Alby sur ChÌ©ran,458,252.0,1/1/02 0:00,45.82133,6.01533
23,Aldsworth,461,700.0,01/01/1835 12:00:00 AM,51.78333,-1.78333
24,Aleppo,462,3200.0,01/01/1873 12:00:00 AM,36.23333,37.13333
25,Alessandria,463,908.0,01/01/1860 12:00:00 AM,44.88333,8.75000
26,Alexandrovsky,465,9251.0,1/1/00 0:00,50.95000,31.81667
27,Alfianello,466,228000.0,01/01/1883 12:00:00 AM,45.26667,10.15000
28,Allegan,2276,32000.0,01/01/1899 12:00:00 AM,42.53333,-85.88333
29,Allende,2278,2000000.0,1/1/69 0:00,26.96667,-105.31667
30,Almahata Sitta,48915,3950.0,1/1/08 0:00,20.74575,32.41275
...,...,...,...,...,...,...
45683,Youanmi,30373,118400.0,1/1/17 0:00,-29.50000,118.75000
45684,Youndegin,30374,3800000.0,01/01/1884 12:00:00 AM,-32.10000,117.71667
45685,Youxi,55793,218000.0,1/1/06 0:00,26.06000,118.01000
45686,Ysleta,30375,140700.0,1/1/14 0:00,31.65000,-106.18333
45687,Yucca 015,57175,3.0,1/1/11 0:00,34.81970,-114.27610
45688,Yucca 016,57158,25.9,1/1/11 0:00,34.82658,-114.27763
45689,Yucca 017,57159,200.0,1/1/11 0:00,34.81923,-114.27735
45690,Yudoma,30376,7600.0,1/1/46 0:00,60.00000,140.00000
45691,Zacatecas (1792),30381,1000000.0,01/01/1792 12:00:00 AM,22.81667,-102.56667
45693,Zaffra,30383,3000.0,1/1/19 0:00,35.00000,-94.75000
45694,Zag (b),30385,300.0,1/1/99 0:00,27.33333,-9.33333
45695,Zagora,30387,50000.0,1/1/87 0:00,30.36667,-5.85000
45696,Zakâodzie,30390,8680.0,1/1/98 0:00,50.76278,22.86611
45697,Zapaliname,30392,85000.0,1/1/98 0:00,25.00944,-100.75000
45699,ZapotitlÌÁn Salinas,30394,27.7,1/1/84 0:00,18.33333,-97.50000
45701,Zegdou,30398,6700.0,1/1/98 0:00,29.75000,-4.50000
45702,Zelfana,31353,1058.0,1/1/02 0:00,32.15833,4.63333
45703,Zenda,30400,3700.0,1/1/55 0:00,42.51333,-88.48944
45704,Zerga,30402,76.0,1/1/73 0:00,20.25000,-12.68333
45705,Zerhamra,30403,630000.0,1/1/67 0:00,29.85861,-2.64500
45706,Zerkaly,31354,16000.0,1/1/56 0:00,52.13333,81.96667
45707,Zhaoping,54609,2000000.0,1/1/83 0:00,24.23333,111.18333
45708,Zhigansk,30405,900000.0,1/1/66 0:00,68.00000,128.30000
45709,Zhongxiang,30406,100000.0,1/1/81 0:00,31.20000,112.50000
45710,Zillah 001,31355,1475.0,1/1/90 0:00,29.03700,17.01850
45711,Zillah 002,31356,172.0,1/1/90 0:00,29.03700,17.01850
45712,Zinder,30409,46.0,1/1/99 0:00,13.78333,8.96667
45713,Zlin,30410,3.3,1/1/39 0:00,49.25000,17.66667
45714,Zubkovsky,31357,2167.0,1/1/03 0:00,49.78917,41.50460
45715,Zulu Queen,30414,200.0,1/1/76 0:00,33.98333,-115.68333

In [21]:
dropped = dropped[dropped.reclat.notnull()]
dropped = dropped[dropped.reclong.notnull()]
dropped

,name,id,mass (g),year,reclat,reclong
0,Aachen,1,21.0,01/01/1880 12:00:00 AM,50.77500,6.08333
1,Aarhus,2,720.0,1/1/51 0:00,56.18333,10.23333
2,Abee,6,107000.0,1/1/52 0:00,54.21667,-113.00000
3,Acapulco,10,1914.0,1/1/76 0:00,16.88333,-99.90000
4,Achiras,370,780.0,1/1/02 0:00,-33.16667,-64.95000
5,Adhi Kot,379,4239.0,1/1/19 0:00,32.10000,71.80000
6,Adzhi-Bogdo (stone),390,910.0,1/1/49 0:00,44.83333,95.16667
7,Agen,392,30000.0,01/01/1814 12:00:00 AM,44.21667,0.61667
8,Aguada,398,1620.0,1/1/30 0:00,-31.60000,-65.23333
9,Aguila Blanca,417,1440.0,1/1/20 0:00,-30.86667,-64.55000
10,Aioun el Atrouss,423,1000.0,1/1/74 0:00,16.39806,-9.57028
11,AÌør,424,24000.0,1/1/25 0:00,19.08333,8.38333
13,Akaba,426,779.0,1/1/49 0:00,29.51667,35.05000
14,Akbarpur,427,1800.0,01/01/1838 12:00:00 AM,29.71667,77.95000
15,Akwanga,432,3000.0,1/1/59 0:00,8.91667,8.43333
16,Akyumak,433,50000.0,1/1/81 0:00,39.91667,42.81667
17,Al Rais,446,160.0,1/1/57 0:00,24.41667,39.51667
18,Al Zarnkh,447,700.0,1/1/01 0:00,13.66033,28.96000
19,Alais,448,6000.0,01/01/1806 12:00:00 AM,44.11667,4.08333
20,Albareto,453,2000.0,01/01/1766 12:00:00 AM,44.65000,11.01667
21,Alberta,454,625.0,1/1/49 0:00,2.00000,22.66667
22,Alby sur ChÌ©ran,458,252.0,1/1/02 0:00,45.82133,6.01533
23,Aldsworth,461,700.0,01/01/1835 12:00:00 AM,51.78333,-1.78333
24,Aleppo,462,3200.0,01/01/1873 12:00:00 AM,36.23333,37.13333
25,Alessandria,463,908.0,01/01/1860 12:00:00 AM,44.88333,8.75000
26,Alexandrovsky,465,9251.0,1/1/00 0:00,50.95000,31.81667
27,Alfianello,466,228000.0,01/01/1883 12:00:00 AM,45.26667,10.15000
28,Allegan,2276,32000.0,01/01/1899 12:00:00 AM,42.53333,-85.88333
29,Allende,2278,2000000.0,1/1/69 0:00,26.96667,-105.31667
30,Almahata Sitta,48915,3950.0,1/1/08 0:00,20.74575,32.41275
...,...,...,...,...,...,...
45683,Youanmi,30373,118400.0,1/1/17 0:00,-29.50000,118.75000
45684,Youndegin,30374,3800000.0,01/01/1884 12:00:00 AM,-32.10000,117.71667
45685,Youxi,55793,218000.0,1/1/06 0:00,26.06000,118.01000
45686,Ysleta,30375,140700.0,1/1/14 0:00,31.65000,-106.18333
45687,Yucca 015,57175,3.0,1/1/11 0:00,34.81970,-114.27610
45688,Yucca 016,57158,25.9,1/1/11 0:00,34.82658,-114.27763
45689,Yucca 017,57159,200.0,1/1/11 0:00,34.81923,-114.27735
45690,Yudoma,30376,7600.0,1/1/46 0:00,60.00000,140.00000
45691,Zacatecas (1792),30381,1000000.0,01/01/1792 12:00:00 AM,22.81667,-102.56667
45693,Zaffra,30383,3000.0,1/1/19 0:00,35.00000,-94.75000
45694,Zag (b),30385,300.0,1/1/99 0:00,27.33333,-9.33333
45695,Zagora,30387,50000.0,1/1/87 0:00,30.36667,-5.85000
45696,Zakâodzie,30390,8680.0,1/1/98 0:00,50.76278,22.86611
45697,Zapaliname,30392,85000.0,1/1/98 0:00,25.00944,-100.75000
45699,ZapotitlÌÁn Salinas,30394,27.7,1/1/84 0:00,18.33333,-97.50000
45701,Zegdou,30398,6700.0,1/1/98 0:00,29.75000,-4.50000
45702,Zelfana,31353,1058.0,1/1/02 0:00,32.15833,4.63333
45703,Zenda,30400,3700.0,1/1/55 0:00,42.51333,-88.48944
45704,Zerga,30402,76.0,1/1/73 0:00,20.25000,-12.68333
45705,Zerhamra,30403,630000.0,1/1/67 0:00,29.85861,-2.64500
45706,Zerkaly,31354,16000.0,1/1/56 0:00,52.13333,81.96667
45707,Zhaoping,54609,2000000.0,1/1/83 0:00,24.23333,111.18333
45708,Zhigansk,30405,900000.0,1/1/66 0:00,68.00000,128.30000
45709,Zhongxiang,30406,100000.0,1/1/81 0:00,31.20000,112.50000
45710,Zillah 001,31355,1475.0,1/1/90 0:00,29.03700,17.01850
45711,Zillah 002,31356,172.0,1/1/90 0:00,29.03700,17.01850
45712,Zinder,30409,46.0,1/1/99 0:00,13.78333,8.96667
45713,Zlin,30410,3.3,1/1/39 0:00,49.25000,17.66667
45714,Zubkovsky,31357,2167.0,1/1/03 0:00,49.78917,41.50460
45715,Zulu Queen,30414,200.0,1/1/76 0:00,33.98333,-115.68333

In [91]:
dataset = dropped[0:100].drop(['id'], axis=1)
dataset

,name,mass (g),year,reclat,reclong
0,Aachen,21.0,01/01/1880 12:00:00 AM,50.77500,6.08333
1,Aarhus,720.0,1/1/51 0:00,56.18333,10.23333
2,Abee,107000.0,1/1/52 0:00,54.21667,-113.00000
3,Acapulco,1914.0,1/1/76 0:00,16.88333,-99.90000
4,Achiras,780.0,1/1/02 0:00,-33.16667,-64.95000
5,Adhi Kot,4239.0,1/1/19 0:00,32.10000,71.80000
6,Adzhi-Bogdo (stone),910.0,1/1/49 0:00,44.83333,95.16667
7,Agen,30000.0,01/01/1814 12:00:00 AM,44.21667,0.61667
8,Aguada,1620.0,1/1/30 0:00,-31.60000,-65.23333
9,Aguila Blanca,1440.0,1/1/20 0:00,-30.86667,-64.55000
10,Aioun el Atrouss,1000.0,1/1/74 0:00,16.39806,-9.57028
11,AÌør,24000.0,1/1/25 0:00,19.08333,8.38333
13,Akaba,779.0,1/1/49 0:00,29.51667,35.05000
14,Akbarpur,1800.0,01/01/1838 12:00:00 AM,29.71667,77.95000
15,Akwanga,3000.0,1/1/59 0:00,8.91667,8.43333
16,Akyumak,50000.0,1/1/81 0:00,39.91667,42.81667
17,Al Rais,160.0,1/1/57 0:00,24.41667,39.51667
18,Al Zarnkh,700.0,1/1/01 0:00,13.66033,28.96000
19,Alais,6000.0,01/01/1806 12:00:00 AM,44.11667,4.08333
20,Albareto,2000.0,01/01/1766 12:00:00 AM,44.65000,11.01667
21,Alberta,625.0,1/1/49 0:00,2.00000,22.66667
22,Alby sur ChÌ©ran,252.0,1/1/02 0:00,45.82133,6.01533
23,Aldsworth,700.0,01/01/1835 12:00:00 AM,51.78333,-1.78333
24,Aleppo,3200.0,01/01/1873 12:00:00 AM,36.23333,37.13333
25,Alessandria,908.0,01/01/1860 12:00:00 AM,44.88333,8.75000
26,Alexandrovsky,9251.0,1/1/00 0:00,50.95000,31.81667
27,Alfianello,228000.0,01/01/1883 12:00:00 AM,45.26667,10.15000
28,Allegan,32000.0,01/01/1899 12:00:00 AM,42.53333,-85.88333
29,Allende,2000000.0,1/1/69 0:00,26.96667,-105.31667
30,Almahata Sitta,3950.0,1/1/08 0:00,20.74575,32.41275
...,...,...,...,...,...
73,Banswal,14.0,1/1/13 0:00,30.40000,78.20000
74,Banten,629.0,1/1/33 0:00,-6.33333,106.00000
75,Barbotan,6400.0,01/01/1790 12:00:00 AM,43.95000,-0.05000
77,Barea,3200.0,01/01/1842 12:00:00 AM,42.38333,-2.50000
78,Barnaul,23.2,1/1/04 0:00,52.73333,84.08333
79,Barntrup,17.0,01/01/1886 12:00:00 AM,52.00000,9.10000
80,Baroti,4500.0,1/1/10 0:00,31.61667,76.80000
81,Barwell,44000.0,1/1/65 0:00,52.56528,-1.33972
82,Bassikounou,29560.0,1/1/06 0:00,15.78333,-5.90000
83,BaszkÌ_wka,15500.0,1/1/94 0:00,52.03333,20.93583
84,Bath,21000.0,01/01/1892 12:00:00 AM,45.41667,-98.31667
85,Bath Furnace,86000.0,1/1/02 0:00,38.25000,-83.75000
86,Battle Mountain,2900.0,1/1/12 0:00,40.66813,-117.18913
87,Bawku,1557.0,1/1/89 0:00,11.08333,-0.18333
88,Baxter,611.0,1/1/16 0:00,36.75000,-93.50000
89,Beardsley,16000.0,1/1/29 0:00,39.80000,-101.20000
90,Beaver Creek,14000.0,01/01/1893 12:00:00 AM,51.16667,-117.33333
91,Beddgelert,794.0,1/1/49 0:00,53.01667,-4.10000
92,Bells,375.0,1/1/61 0:00,33.60000,-96.46667
94,Benares (a),3700.0,01/01/1798 12:00:00 AM,25.36667,82.91667
95,Benguerir,25000.0,1/1/04 0:00,32.25000,-8.15000
96,Beni M'hira,19000.0,1/1/01 0:00,32.86667,10.80000
97,Benld,1770.5,1/1/38 0:00,39.08333,-89.15000
98,Benoni,3880.0,1/1/43 0:00,-26.16667,28.41667
99,Bensour,45000.0,1/1/02 0:00,30.00000,-7.00000
100,Benton,2840.0,1/1/49 0:00,45.95000,-67.55000
101,Berduc,270.0,1/1/08 0:00,-31.91000,-58.32833
102,BÌ©rÌ©ba,18000.0,1/1/24 0:00,11.65000,-3.65000
103,Berlanguillas,1440.0,01/01/1811 12:00:00 AM,41.68333,-3.80000
104,Berthoud,960.0,1/1/04 0:00,40.30583,-105.02325

In [57]:
def find_nth(haystack, needle, n):
    start = haystack.find(needle)
    while start >= 0 and n > 1:
        start = haystack.find(needle, start+len(needle))
        n -= 1
    return start

In [92]:
year =  dataset['year']
new_years = []
for y in year.iteritems():
    i = find_nth(y[1], '/', 2)
    space = find_nth(y[1], ' ', 1)
    real_yr = y[1][i+1:space]
    #lol 90s
    if int(real_yr) < 18:
        real_yr = str(int(real_yr) + 2000)
    elif int(real_yr) < 100:
        real_yr = str(int(real_yr) + 1900)
    print(real_yr)
    new_years.append(int(real_yr))

1880
1951
1952
1976
2002
1919
1949
1814
1930
1920
1974
1925
1949
1838
1959
1981
1957
2001
1806
1766
1949
2002
1835
1873
1860
2000
1883
1899
1969
2008
1977
1895
1880
1898
1969
1939
1869
1942
1971
1984
2014
1803
1954
1932
1950
1805
2009
1923
1886
1920
1896
1933
1945
1836
1865
1842
1858
1952
2008
1855
1968
1938
1814
1934
1929
1922
2007
1993
1871
1892
2013
1933
1790
1842
2004
1886
2010
1965
2006
1994
1892
2002
2012
1989
2016
1929
1893
1949
1961
1798
2004
2001
1938
1943
2002
1949
2008
1924
1811
2004

In [96]:
dataset['year'] = new_year_row

dataset = dataset[0:95]

## saving to json

In [100]:
# save to json
json_data = []
for row in dataset.iterrows():
    i, d = row
    json_data.append(d.tolist())
json_data

[['Aachen', 21.0, '1880', 50.775, 6.08333],
 ['Aarhus', 720.0, '1951', 56.183330000000005, 10.23333],
 ['Abee', 107000.0, '1952', 54.21666999999999, -113.0],
 ['Acapulco', 1914.0, '1976', 16.883329999999997, -99.9],
 ['Achiras', 780.0, '2002', -33.16667, -64.95],
 ['Adhi Kot', 4239.0, '1919', 32.1, 71.8],
 ['Adzhi-Bogdo (stone)', 910.0, '1949', 44.83333, 95.16667],
 ['Agen', 30000.0, '1814', 44.21667, 0.6166699999999999],
 ['Aguada', 1620.0, '1930', -31.6, -65.23333000000001],
 ['Aguila Blanca', 1440.0, '1920', -30.866670000000003, -64.55],
 ['Aioun el Atrouss', 1000.0, '1974', 16.39806, -9.57028],
 ['AÌør', 24000.0, '1925', 19.08333, 8.38333],
 ['Akaba', 779.0, '1838', 29.51667, 35.05],
 ['Akbarpur', 1800.0, '1959', 29.71667, 77.95],
 ['Akwanga', 3000.0, '1981', 8.91667, 8.43333],
 ['Akyumak', 50000.0, '1957', 39.91667, 42.81667],
 ['Al Rais', 160.0, '2001', 24.41667, 39.51667],
 ['Al Zarnkh', 700.0, '1806', 13.660329999999998, 28.96],
 ['Alais', 6000.0, '1766', 44.11667, 4.08333],
 ['Albareto', 2000.0, '1949', 44.65, 11.01667],
 ['Alberta', 625.0, '2002', 2.0, 22.66667],
 ['Alby sur ChÌ©ran', 252.0, '1835', 45.821329999999996, 6.0153300000000005],
 ['Aldsworth', 700.0, '1873', 51.78333, -1.7833299999999999],
 ['Aleppo', 3200.0, '1860', 36.23333, 37.13333],
 ['Alessandria', 908.0, '2000', 44.88333, 8.75],
 ['Alexandrovsky', 9251.0, '1883', 50.95, 31.816670000000002],
 ['Alfianello', 228000.0, '1899', 45.26667, 10.15],
 ['Allegan', 32000.0, '1969', 42.53333, -85.88333],
 ['Allende', 2000000.0, '2008', 26.96667, -105.31667],
 ['Almahata Sitta', 3950.0, '1977', 20.74575, 32.41275],
 ["Alta'ameem", 6000.0, '1895', 35.27333, 44.215559999999996],
 ['Ambapur Nagla', 6400.0, '1880', 27.66667, 78.25],
 ['Andhara', 2700.0, '1898', 26.58333, 85.56667],
 ['Andover', 3200.0, '1969', 44.61667, -70.75],
 ['Andreevka', 600.0, '1939', 48.7, 37.5],
 ['Andura', 17900.0, '1869', 20.883329999999997, 76.86667],
 ['Angra dos Reis (stone)', 1500.0, '1984', -22.96667, -44.31667],
 ['Ankober', 6500.0, '2014', 9.53333, 39.71667],
 ['Anlong', 2500.0, '1803', 25.15, 105.18333],
 ['Aomori', 320.0, '1954', 40.810559999999995, 140.78556],
 ['Appley Bridge', 15000.0, '1932', 53.583330000000004, -2.71667],
 ['Apt', 3200.0, '1950', 43.86667, 5.38333],
 ['Arbol Solo', 810.0, '1805', -33.0, -66.0],
 ['Archie', 5070.0, '2009', 38.5, -94.3],
 ['Arroyo Aguiar', 7450.0, '1923', -31.41667, -60.666669999999996],
 ['Asco', 41.0, '1886', 42.45, 9.03333],
 ['Ash Creek', 9500.0, '1920', 31.805, -97.01],
 ['Ashdon', 1300.0, '1896', 52.05, 0.3],
 ['Assisi', 2000.0, '1933', 43.03333, 12.55],
 ['Atarra', 1280.0, '1945', 25.254170000000002, 80.625],
 ['Atemajac', 94.2, '1836', 20.066670000000002, -103.66667],
 ['Athens', 265.0, '1865', 34.75, -87.0],
 ['Atoka', 1384.2, '1842', 34.31667, -96.15],
 ['Aubres', 800.0, '1858', 44.38333, 5.16667],
 ['Aumale', 50000.0, '1952', 36.16667, 3.66667],
 ['Aumieres', 2000.0, '2008', 44.33333, 3.23333],
 ['Ausson', 50000.0, '1855', 43.08333, 0.58333],
 ['Avanhandava', 9330.0, '1968', -21.460279999999997, -49.950829999999996],
 ['Avce', 1230.0, '1938', 46.0, 13.5],
 ['Avilez', 146.0, '1814', 25.0, -103.5],
 ['Awere', 134.0, '1934', 2.71667, 32.83333],
 ['Aztec', 2830.0, '1929', 36.8, -108.0],
 ['Bachmut', 18000.0, '1922', 48.6, 38.0],
 ['Bahjoi', 10322.0, '2007', 28.48333, 78.5],
 ['Bald Mountain', 3700.0, '1993', 35.96667, -82.48333000000001],
 ['Baldwyn', 345.0, '1871', 34.5, -88.66667],
 ['Bali', 1000.0, '1892', 5.38333, 16.383329999999997],
 ['Ban Rong Du', 16700.0, '2013', 16.66667, 101.18333],
 ['Bandong', 11500.0, '1933', -6.91667, 107.6],
 ['Bansur', 15000.0, '1790', 27.7, 76.33333],
 ['Banswal', 14.0, '1842', 30.4, 78.2],
 ['Banten', 629.0, '2004', -6.33333, 106.0],
 ['Barbotan', 6400.0, '1886', 43.95, -0.05],
 ['Barea', 3200.0, '1965', 42.38333, -2.5],
 ['Barnaul', 23.2, '2006', 52.73333, 84.08333],
 ['Barntrup', 17.0, '1994', 52.0, 9.1],
 ['Baroti', 4500.0, '1892', 31.616670000000003, 76.8],
 ['Barwell', 44000.0, '2002', 52.56528, -1.33972],
 ['Bassikounou', 29560.0, '2012', 15.78333, -5.9],
 ['BaszkÌ_wka', 15500.0, '1989', 52.03333, 20.93583],
 ['Bath', 21000.0, '2016', 45.41667, -98.31667],
 ['Bath Furnace', 86000.0, '1929', 38.25, -83.75],
 ['Battle Mountain', 2900.0, '1893', 40.66813, -117.18913],
 ['Bawku', 1557.0, '1949', 11.08333, -0.18333],
 ['Baxter', 611.0, '1961', 36.75, -93.5],
 ['Beardsley', 16000.0, '1798', 39.8, -101.2],
 ['Beaver Creek', 14000.0, '2004', 51.16667, -117.33333],
 ['Beddgelert', 794.0, '2001', 53.01667, -4.1],
 ['Bells', 375.0, '1938', 33.6, -96.46667],
 ['Benares (a)', 3700.0, '2002', 25.366670000000003, 82.91667],
 ['Benguerir', 25000.0, '1949', 32.25, -8.15],
 ["Beni M'hira", 19000.0, '2008', 32.86667, 10.8],
 ['Benld', 1770.5, '1924', 39.08333, -89.15],
 ['Benoni', 3880.0, '1811', -26.16667, 28.41667],
 ['Bensour', 45000.0, '2004', 30.0, -7.0]]

In [ ]:
headers = list(dataset)

In [101]:
final_json = {}

headers = ['name', 'mass', 'year', 'reclat', 'reclong'] #manually adjust header names
final_json["name"] = "Meteor" #manually name json

final_json["id"] = str(uuid.uuid4())
final_json["classType"] = "imported"

initsig = {}
for header in headers:
    initsig[header] = []

final_json["initializedSignals"] = initsig

#switch mass and year, only extract year
# mic - assume limits 0-300 a, 0-4000 f

In [102]:
#custom dict for signal info, manually change this too
signalList = [
     {'name' : {'displayName': 'Name', 'classType' : 'string', 'fieldName' : 'name'}},
     {'mass' : {'displayName': 'Mass (g)', 'classType' : 'number', 'fieldName' : 'mass'}},
     {'year' : {'displayName': 'Year', 'classType' : 'date', 'fieldName' : 'year'}},
     {'reclat' : {'displayName': 'Latitude', 'classType' : 'number', 'fieldName' : 'reclat'}},
     {'reclong' : {'displayName': 'Longitude', 'classType' : 'number', 'fieldName' : 'reclong'}},
]

In [103]:
signals = []
i = 0
for signalDict in signalList:
    signal = {}
    signal["id"] = str(uuid.uuid4())
    signal["order"] = i
    signal["style"] = "imported"
    signal["settings"] = {}

    for key, val in signalDict.items(): #only loops once 
        signal["displayName"] = signalDict[key]["displayName"]
        signal["classType"] = signalDict[key]["classType"]
        signal["fieldName"] = signalDict[key]["fieldName"]
    
    i += 1
    signals.append(signal)
signals

[{'classType': 'string',
  'displayName': 'Name',
  'fieldName': 'name',
  'id': '7da0d8f5-85af-4156-b8ae-0edf4bc1d34b',
  'order': 0,
  'settings': {},
  'style': 'imported'},
 {'classType': 'number',
  'displayName': 'Mass (g)',
  'fieldName': 'mass',
  'id': '504e74eb-94fd-425f-8d05-3ed4702d59c5',
  'order': 1,
  'settings': {},
  'style': 'imported'},
 {'classType': 'date',
  'displayName': 'Year',
  'fieldName': 'year',
  'id': '71381023-c4f5-494c-8bba-2170b578b677',
  'order': 2,
  'settings': {},
  'style': 'imported'},
 {'classType': 'number',
  'displayName': 'Latitude',
  'fieldName': 'reclat',
  'id': '817c5626-9cc4-48d8-8f5c-0b5a3e56f8de',
  'order': 3,
  'settings': {},
  'style': 'imported'},
 {'classType': 'number',
  'displayName': 'Longitude',
  'fieldName': 'reclong',
  'id': '7bfdd997-5244-415f-bd4b-346b34acaa59',
  'order': 4,
  'settings': {},
  'style': 'imported'}]

In [104]:
final_json["signals"] = signals
final_json["data"] = json_data

final_json

{'classType': 'imported',
 'data': [['Aachen', 21.0, '1880', 50.775, 6.08333],
  ['Aarhus', 720.0, '1951', 56.183330000000005, 10.23333],
  ['Abee', 107000.0, '1952', 54.21666999999999, -113.0],
  ['Acapulco', 1914.0, '1976', 16.883329999999997, -99.9],
  ['Achiras', 780.0, '2002', -33.16667, -64.95],
  ['Adhi Kot', 4239.0, '1919', 32.1, 71.8],
  ['Adzhi-Bogdo (stone)', 910.0, '1949', 44.83333, 95.16667],
  ['Agen', 30000.0, '1814', 44.21667, 0.6166699999999999],
  ['Aguada', 1620.0, '1930', -31.6, -65.23333000000001],
  ['Aguila Blanca', 1440.0, '1920', -30.866670000000003, -64.55],
  ['Aioun el Atrouss', 1000.0, '1974', 16.39806, -9.57028],
  ['AÌør', 24000.0, '1925', 19.08333, 8.38333],
  ['Akaba', 779.0, '1838', 29.51667, 35.05],
  ['Akbarpur', 1800.0, '1959', 29.71667, 77.95],
  ['Akwanga', 3000.0, '1981', 8.91667, 8.43333],
  ['Akyumak', 50000.0, '1957', 39.91667, 42.81667],
  ['Al Rais', 160.0, '2001', 24.41667, 39.51667],
  ['Al Zarnkh', 700.0, '1806', 13.660329999999998, 28.96],
  ['Alais', 6000.0, '1766', 44.11667, 4.08333],
  ['Albareto', 2000.0, '1949', 44.65, 11.01667],
  ['Alberta', 625.0, '2002', 2.0, 22.66667],
  ['Alby sur ChÌ©ran', 252.0, '1835', 45.821329999999996, 6.0153300000000005],
  ['Aldsworth', 700.0, '1873', 51.78333, -1.7833299999999999],
  ['Aleppo', 3200.0, '1860', 36.23333, 37.13333],
  ['Alessandria', 908.0, '2000', 44.88333, 8.75],
  ['Alexandrovsky', 9251.0, '1883', 50.95, 31.816670000000002],
  ['Alfianello', 228000.0, '1899', 45.26667, 10.15],
  ['Allegan', 32000.0, '1969', 42.53333, -85.88333],
  ['Allende', 2000000.0, '2008', 26.96667, -105.31667],
  ['Almahata Sitta', 3950.0, '1977', 20.74575, 32.41275],
  ["Alta'ameem", 6000.0, '1895', 35.27333, 44.215559999999996],
  ['Ambapur Nagla', 6400.0, '1880', 27.66667, 78.25],
  ['Andhara', 2700.0, '1898', 26.58333, 85.56667],
  ['Andover', 3200.0, '1969', 44.61667, -70.75],
  ['Andreevka', 600.0, '1939', 48.7, 37.5],
  ['Andura', 17900.0, '1869', 20.883329999999997, 76.86667],
  ['Angra dos Reis (stone)', 1500.0, '1984', -22.96667, -44.31667],
  ['Ankober', 6500.0, '2014', 9.53333, 39.71667],
  ['Anlong', 2500.0, '1803', 25.15, 105.18333],
  ['Aomori', 320.0, '1954', 40.810559999999995, 140.78556],
  ['Appley Bridge', 15000.0, '1932', 53.583330000000004, -2.71667],
  ['Apt', 3200.0, '1950', 43.86667, 5.38333],
  ['Arbol Solo', 810.0, '1805', -33.0, -66.0],
  ['Archie', 5070.0, '2009', 38.5, -94.3],
  ['Arroyo Aguiar', 7450.0, '1923', -31.41667, -60.666669999999996],
  ['Asco', 41.0, '1886', 42.45, 9.03333],
  ['Ash Creek', 9500.0, '1920', 31.805, -97.01],
  ['Ashdon', 1300.0, '1896', 52.05, 0.3],
  ['Assisi', 2000.0, '1933', 43.03333, 12.55],
  ['Atarra', 1280.0, '1945', 25.254170000000002, 80.625],
  ['Atemajac', 94.2, '1836', 20.066670000000002, -103.66667],
  ['Athens', 265.0, '1865', 34.75, -87.0],
  ['Atoka', 1384.2, '1842', 34.31667, -96.15],
  ['Aubres', 800.0, '1858', 44.38333, 5.16667],
  ['Aumale', 50000.0, '1952', 36.16667, 3.66667],
  ['Aumieres', 2000.0, '2008', 44.33333, 3.23333],
  ['Ausson', 50000.0, '1855', 43.08333, 0.58333],
  ['Avanhandava', 9330.0, '1968', -21.460279999999997, -49.950829999999996],
  ['Avce', 1230.0, '1938', 46.0, 13.5],
  ['Avilez', 146.0, '1814', 25.0, -103.5],
  ['Awere', 134.0, '1934', 2.71667, 32.83333],
  ['Aztec', 2830.0, '1929', 36.8, -108.0],
  ['Bachmut', 18000.0, '1922', 48.6, 38.0],
  ['Bahjoi', 10322.0, '2007', 28.48333, 78.5],
  ['Bald Mountain', 3700.0, '1993', 35.96667, -82.48333000000001],
  ['Baldwyn', 345.0, '1871', 34.5, -88.66667],
  ['Bali', 1000.0, '1892', 5.38333, 16.383329999999997],
  ['Ban Rong Du', 16700.0, '2013', 16.66667, 101.18333],
  ['Bandong', 11500.0, '1933', -6.91667, 107.6],
  ['Bansur', 15000.0, '1790', 27.7, 76.33333],
  ['Banswal', 14.0, '1842', 30.4, 78.2],
  ['Banten', 629.0, '2004', -6.33333, 106.0],
  ['Barbotan', 6400.0, '1886', 43.95, -0.05],
  ['Barea', 3200.0, '1965', 42.38333, -2.5],
  ['Barnaul', 23.2, '2006', 52.73333, 84.08333],
  ['Barntrup', 17.0, '1994', 52.0, 9.1],
  ['Baroti', 4500.0, '1892', 31.616670000000003, 76.8],
  ['Barwell', 44000.0, '2002', 52.56528, -1.33972],
  ['Bassikounou', 29560.0, '2012', 15.78333, -5.9],
  ['BaszkÌ_wka', 15500.0, '1989', 52.03333, 20.93583],
  ['Bath', 21000.0, '2016', 45.41667, -98.31667],
  ['Bath Furnace', 86000.0, '1929', 38.25, -83.75],
  ['Battle Mountain', 2900.0, '1893', 40.66813, -117.18913],
  ['Bawku', 1557.0, '1949', 11.08333, -0.18333],
  ['Baxter', 611.0, '1961', 36.75, -93.5],
  ['Beardsley', 16000.0, '1798', 39.8, -101.2],
  ['Beaver Creek', 14000.0, '2004', 51.16667, -117.33333],
  ['Beddgelert', 794.0, '2001', 53.01667, -4.1],
  ['Bells', 375.0, '1938', 33.6, -96.46667],
  ['Benares (a)', 3700.0, '2002', 25.366670000000003, 82.91667],
  ['Benguerir', 25000.0, '1949', 32.25, -8.15],
  ["Beni M'hira", 19000.0, '2008', 32.86667, 10.8],
  ['Benld', 1770.5, '1924', 39.08333, -89.15],
  ['Benoni', 3880.0, '1811', -26.16667, 28.41667],
  ['Bensour', 45000.0, '2004', 30.0, -7.0]],
 'id': 'cba7cc12-9da3-4959-8df1-238c080439eb',
 'initializedSignals': {'mass': [],
  'name': [],
  'reclat': [],
  'reclong': [],
  'year': []},
 'name': 'Meteor',
 'signals': [{'classType': 'string',
   'displayName': 'Name',
   'fieldName': 'name',
   'id': '7da0d8f5-85af-4156-b8ae-0edf4bc1d34b',
   'order': 0,
   'settings': {},
   'style': 'imported'},
  {'classType': 'number',
   'displayName': 'Mass (g)',
   'fieldName': 'mass',
   'id': '504e74eb-94fd-425f-8d05-3ed4702d59c5',
   'order': 1,
   'settings': {},
   'style': 'imported'},
  {'classType': 'date',
   'displayName': 'Year',
   'fieldName': 'year',
   'id': '71381023-c4f5-494c-8bba-2170b578b677',
   'order': 2,
   'settings': {},
   'style': 'imported'},
  {'classType': 'number',
   'displayName': 'Latitude',
   'fieldName': 'reclat',
   'id': '817c5626-9cc4-48d8-8f5c-0b5a3e56f8de',
   'order': 3,
   'settings': {},
   'style': 'imported'},
  {'classType': 'number',
   'displayName': 'Longitude',
   'fieldName': 'reclong',
   'id': '7bfdd997-5244-415f-bd4b-346b34acaa59',
   'order': 4,
   'settings': {},
   'style': 'imported'}]}

In [105]:
with open ('meteor.json', 'w') as outfile:
    json.dump(final_json, outfile)

In [3]:
data = [0.5,
 0.5031466114181192,
 0.5065681904222099,
 0.5089639054926879,
 0.5091235904966663,
 0.5070362775877058,
 0.5040328637344492,
 0.5019629108781443,
 0.5014092809427584,
 0.5005929142356635,
 0.4989035414205588,
 0.4969937983905978,
 0.49554945698122743,
 0.494666042935723,
 0.49374796753591194,
 0.4919301728980843,
 0.48898818979978104,
 0.48502912662803294,
 0.4797969954106296,
 0.4738302883139864,
 0.46808044494674284,
 0.46346852760701257,
 0.4605245467508332,
 0.4591094366818187,
 0.4583712131475407,
 0.4585223651163826,
 0.45900727878183845,
 0.4578383176395931,
 0.45346450645405695,
 0.4457618702180861,
 0.43605580213180783,
 0.4261754606005524,
 0.4165070332524723,
 0.4057523265139351,
 0.39530957923927773,
 0.3879330576659167,
 0.38539952973741387,
 0.3874992810866773,
 0.3923615707587993,
 0.3981145266735322,
 0.4048670974637132,
 0.4118538729591154,
 0.41772279890711494,
 0.4219286302530313,
 0.42499268578881466,
 0.4282582484476407,
 0.4331418182344752,
 0.43988328741341204,
 0.44796217241326003,
 0.4583342707505868,
 0.469632747090214,
 0.47952924339254654,
 0.486341761174628,
 0.4897418879246465,
 0.49056136766988806,
 0.4896904288775553,
 0.48653158005035646,
 0.4814965350091918,
 0.4769022345926019,
 0.47471409079189575,
 0.4752623707518724,
 0.47715916732918334,
 0.47841595620833227,
 0.4787270271496451,
 0.4802123759843091,
 0.4829783075654122,
 0.4854433343597617,
 0.4863478786158493,
 0.48575085052146055,
 0.48497565224852673,
 0.4855056078852193,
 0.4868952082601516,
 0.4870001607585859,
 0.4863822938999006,
 0.48705485392399933,
 0.4903180386063734,
 0.4958088373157678,
 0.5017766428969624,
 0.5065846353786693,
 0.5108222388002209,
 0.5149864918686251,
 0.5181138154782796,
 0.5194493532106611,
 0.5192722459844176,
 0.5189362869593361,
 0.5201268668476384,
 0.5233343331838134,
 0.5266123067596168,
 0.5287225205733285,
 0.5297858254750678,
 0.5302667543010386,
 0.5304397725488187,
 0.5302099924289121,
 0.5292883502925644,
 0.5277065979098441,
 0.5250410876365905,
 0.5200417274715174,
 0.5132986535727021,
 0.5064448585041565,
 0.5012087318454366,
 0.4987547608747972,
 0.4993123913258908,
 0.5021715350378145,
 0.5075651824577254,
 0.5150086469601562,
 0.5219507955469299,
 0.5261273008771106,
 0.5269353344200389,
 0.5256080396456136,
 0.5241887852518122,
 0.523528570119169,
 0.524108642608848,
 0.52694679616542,
 0.5321146006823577,
 0.5385921009199703,
 0.5445840406663216,
 0.5482635721391217,
 0.548943450628586,
 0.5481355756554676,
 0.5469691724490546,
 0.5461947019907601,
 0.5465751688448742,
 0.5484068524263787,
 0.551374407425115,
 0.5547458977040847,
 0.557907763671875,
 0.5606737752398997,
 0.5624835290027648,
 0.5637600180690191,
 0.5654643487800319,
 0.5683512267429828,
 0.5725600224651345,
 0.5775414165893896,
 0.5823171499787962,
 0.5855331107044575,
 0.5858038745512131,
 0.583162676555752,
 0.5787178468187489,
 0.5740557561048615,
 0.5706291339766463,
 0.5691307594623913,
 0.5688989158541837,
 0.5692123510287094,
 0.56962935497155,
 0.5687406604244842,
 0.5655879806211266,
 0.560468126115177,
 0.5548827548404363,
 0.5506337554025794,
 0.5481648319929138,
 0.5469153177323844,
 0.5473666881086349,
 0.5500188203498739,
 0.5546775067651416,
 0.560309669751591,
 0.5654450383029921,
 0.569124286019458,
 0.571886206068935,
 0.5731449000377911,
 0.572413502107205,
 0.5703253596604823,
 0.5678502897169928,
 0.5657643377681214,
 0.5643906645636559,
 0.5636115608486143,
 0.5629482339803369,
 0.5615160044214582,
 0.5592753043994433,
 0.5569849479974414,
 0.5557326381751768,
 0.5564738748005738,
 0.5595793353312931,
 0.5643906875620105,
 0.569018685822208,
 0.5720049529892571,
 0.5734138033718622,
 0.5741521069967793,
 0.5752942226099298,
 0.5775568331046346,
 0.5809236833769668,
 0.5844451404173242,
 0.5875808370743485,
 0.5901734765426675,
 0.5908967217471314,
 0.5888300382576039,
 0.5843727256687483,
 0.5791696784379983,
 0.5750488761817107,
 0.5721559077399081,
 0.570741218022124,
 0.5718699154116493,
 0.5749761463929731,
 0.5786521375473277,
 0.5814432332613889,
 0.5824798925113561,
 0.5819466447224101,
 0.5810327609663308,
 0.5794271446015262,
 0.5780733413554787,
 0.5791703922198544,
 0.5839364362140721,
 0.5916566458761866,
 0.600056501865453,
 0.607000406676573,
 0.6122848301586726,
 0.6139502956373791,
 0.611001186910653,
 0.6045686604087961,
 0.596919123512637,
 0.5904694785686486,
 0.5868123249033526,
 0.5857514008637887,
 0.5856936087192358,
 0.5861736535819815,
 0.5856829393769575,
 0.5828481999326685,
 0.5776122194100458,
 0.5713738895284907,
 0.5660876035891012,
 0.5623306997844647,
 0.5583207489363277,
 0.5537552540108271,
 0.5497096813952354,
 0.5471406261037582,
 0.5461189796510904,
 0.545750926451378,
 0.5447867687425937,
 0.5429329254143328,
 0.541960977851016,
 0.5421665171974486,
 0.5418315295436283,
 0.539359045619357,
 0.534461266318853,
 0.5282844814139431,
 0.522470781455839,
 0.517375782748185,
 0.5132426497921413,
 0.5114046696473886,
 0.5124889370120511,
 0.5158905676643555,
 0.519878742033915,
 0.522303025531581,
 0.5218999656378628,
 0.5194416232268811,
 0.514667496534455,
 0.5080301020131435,
 0.5010739902159238,
 0.49516662479662893,
 0.49082065502578437,
 0.48761646506501294,
 0.484725,
 0.4817217160032171,
 0.47810455359515447,
 0.4734112477387075,
 0.46772851661927656,
 0.4617879383241291,
 0.4567060220293728,
 0.45336847369453614,
 0.451464449910793,
 0.4497431068450214,
 0.4479051093167798,
 0.4450846413121916,
 0.440439614598061,
 0.4337567965255771,
 0.42561358057478654,
 0.41709639963983425,
 0.40907846216440247,
 0.40164107613332267,
 0.39519614181936874,
 0.39054836536721627,
 0.38823561996036104,
 0.3882091296454857,
 0.3898835171165262,
 0.3925567154584343,
 0.39610722531121034,
 0.40028118626946146,
 0.40450182120407385,
 0.4085977494341827,
 0.4125741843692571,
 0.416452652466059,
 0.42021792084477705,
 0.42387213356433373,
 0.4273606904689405,
 0.4294002329877379,
 0.4293797294257575,
 0.42788995912525707,
 0.42599540971100014,
 0.4246856696765368,
 0.4245165121200585,
 0.4254406696298274,
 0.4269051456710331,
 0.4283514802355232,
 0.4293380135166338,
 0.4297700906452683,
 0.4300112304112266,
 0.43074624999092537,
 0.4325963219904885,
 0.43548738737594966,
 0.43883773428535067,
 0.44297353915274834,
 0.44747028478515816,
 0.451500873021234,
 0.4543881892061281,
 0.45586329756656163,
 0.4560292674861076,
 0.455045013356416,
 0.4534578604905331,
 0.4521364567402988,
 0.4510716698058002,
 0.44985302324240406,
 0.4481075421686904,
 0.4457317816414383,
 0.4429170376976655,
 0.43990028508962653,
 0.43590489545874456,
 0.43135112121167596,
 0.4283102920709247,
 0.4285520297639102,
 0.432462929467874,
 0.43894077545399374,
 0.4462642909307082,
 0.4537692059534712,
 0.46127396922810315,
 0.46739316167696776,
 0.47081803491549407,
 0.4712338139557211,
 0.46954330155327323,
 0.46740253318355773,
 0.46606848264719164,
 0.46492816855075986,
 0.46317944966495395,
 0.46146400075989175,
 0.46081701059086644,
 0.4618865355207195,
 0.46458244362054685,
 0.4681545362707688,
 0.4716999835571973,
 0.47537741886241924,
 0.47979702634060545,
 0.4834812374099884,
 0.48453285385295997,
 0.48209260560339656,
 0.47682505776488754,
 0.47043286685986685,
 0.4642056332796168,
 0.45802599445286235,
 0.4526821981791628,
 0.4494472230091599,
 0.4488706275085364,
 0.45030605528065354,
 0.4521436557729894,
 0.45274742086737163,
 0.45199651142277353,
 0.45007337819439186,
 0.44643872190848866,
 0.44174457758550056,
 0.437029674928842,
 0.43306954910840656,
 0.43008136026050275,
 0.42778342170422223,
 0.42565548547243603,
 0.4220296011496883,
 0.41595690719982215,
 0.40825224575402874,
 0.40063282545426954,
 0.3949252387524502,
 0.39237926489396113,
 0.3930884585855883,
 0.3960615364265592,
 0.401492186770307,
 0.4079822894198771,
 0.4131493538913086,
 0.4155266217998467,
 0.4153521436959229,
 0.414238916849728,
 0.413726083984375,
 0.4133459851700061,
 0.41289427806923534,
 0.41397053243977044,
 0.418023892957897,
 0.42510637323294126,
 0.43365492394521665,
 0.4413022751074622,
 0.4467068708357729,
 0.4497369303768277,
 0.4490185745545213,
 0.4451297472731783,
 0.43999468809464837,
 0.4357647768187899,
 0.4339401862858688,
 0.4347323434008744,
 0.43671732937710955,
 0.43865925060389455,
 0.43982897512310015,
 0.43860519543053655,
 0.43408617712672304,
 0.42692532804360844,
 0.4191216590177258,
 0.41276513630978173,
 0.40802505324926047,
 0.4053623430674903,
 0.40546941877469317,
 0.4071083767073107,
 0.408332693095221,
 0.40749092764640227,
 0.40388573291276164,
 0.39808816943712827,
 0.39186250196962513,
 0.38719161001471986,
 0.38522132740003506,
 0.38598247924394186,
 0.3884567831530223,
 0.390998604507784,
 0.392113443495888,
 0.391593153892903,
 0.3914692025269595,
 0.3935195893613292,
 0.3979811783104853,
 0.4041461247752398,
 0.4108312179186712,
 0.416853657388228,
 0.4215133547179868,
 0.4250806006057156,
 0.42844134280591223,
 0.4317259303516026,
 0.4354222113872473,
 0.4399072286324239,
 0.4450076952703485,
 0.45000475435075027,
 0.4540830217071157,
 0.4572133238023473,
 0.4603122878277328,
 0.46356881630265895,
 0.4667529569398437,
 0.4696341340087773,
 0.4721752201171687,
 0.47455802913886924,
 0.4770402302882666,
 0.47959653952855047,
 0.48113312210116965,
 0.48153016451296116,
 0.48211737440427804,
 0.48419271688830656,
 0.48814234420041497,
 0.4932402547938401,
 0.4981276818817345,
 0.5017945399522643,
 0.5030742909482165,
 0.5011391220731543,
 0.49640128369068903,
 0.4903034434366233,
 0.4848116729270746,
 0.4816250944776906,
 0.4811021878339603,
 0.4817358182088732,
 0.4832161751872419,
 0.4846391571448248,
 0.484671888244605,
 0.482742845165178,
 0.47946148777801717,
 0.4762650176010386,
 0.47429252406313543,
 0.47384991971629875,
 0.4762314144862431,
 0.48114876062903805,
 0.48698230813252313,
 0.49174997795712094,
 0.49391622542084074,
 0.49304099372847227,
 0.4902523823699218,
 0.4868285814003869,
 0.4832484496542298,
 0.4812694453602323,
 0.48229749708710856,
 0.4862933067486088,
 0.4917268223282102,
 0.49657988032340744,
 0.5003485560757963,
 0.5042844371528119,
 0.5080216577153585,
 0.5103865244196767,
 0.5106785081127234,
 0.509222242542397,
 0.5072166574505266,
 0.5058812460486367,
 0.5049375718336656,
 0.5027095197740519,
 0.49963525740782877,
 0.4975102871435077,
 0.4977531108627907,
 0.5005246694566698,
 0.5047166393278936,
 0.5088085858597832,
 0.5123974403135193,
 0.5155149761777937,
 0.5170373488496202,
 0.5159455525907701,
 0.5122812866818396,
 0.5073079624261799,
 0.5028770835501934]

real_data = []
for d in data:
    real_data.append([d])
real_data

[[0.5],
 [0.5031466114181192],
 [0.5065681904222099],
 [0.5089639054926879],
 [0.5091235904966663],
 [0.5070362775877058],
 [0.5040328637344492],
 [0.5019629108781443],
 [0.5014092809427584],
 [0.5005929142356635],
 [0.4989035414205588],
 [0.4969937983905978],
 [0.49554945698122743],
 [0.494666042935723],
 [0.49374796753591194],
 [0.4919301728980843],
 [0.48898818979978104],
 [0.48502912662803294],
 [0.4797969954106296],
 [0.4738302883139864],
 [0.46808044494674284],
 [0.46346852760701257],
 [0.4605245467508332],
 [0.4591094366818187],
 [0.4583712131475407],
 [0.4585223651163826],
 [0.45900727878183845],
 [0.4578383176395931],
 [0.45346450645405695],
 [0.4457618702180861],
 [0.43605580213180783],
 [0.4261754606005524],
 [0.4165070332524723],
 [0.4057523265139351],
 [0.39530957923927773],
 [0.3879330576659167],
 [0.38539952973741387],
 [0.3874992810866773],
 [0.3923615707587993],
 [0.3981145266735322],
 [0.4048670974637132],
 [0.4118538729591154],
 [0.41772279890711494],
 [0.4219286302530313],
 [0.42499268578881466],
 [0.4282582484476407],
 [0.4331418182344752],
 [0.43988328741341204],
 [0.44796217241326003],
 [0.4583342707505868],
 [0.469632747090214],
 [0.47952924339254654],
 [0.486341761174628],
 [0.4897418879246465],
 [0.49056136766988806],
 [0.4896904288775553],
 [0.48653158005035646],
 [0.4814965350091918],
 [0.4769022345926019],
 [0.47471409079189575],
 [0.4752623707518724],
 [0.47715916732918334],
 [0.47841595620833227],
 [0.4787270271496451],
 [0.4802123759843091],
 [0.4829783075654122],
 [0.4854433343597617],
 [0.4863478786158493],
 [0.48575085052146055],
 [0.48497565224852673],
 [0.4855056078852193],
 [0.4868952082601516],
 [0.4870001607585859],
 [0.4863822938999006],
 [0.48705485392399933],
 [0.4903180386063734],
 [0.4958088373157678],
 [0.5017766428969624],
 [0.5065846353786693],
 [0.5108222388002209],
 [0.5149864918686251],
 [0.5181138154782796],
 [0.5194493532106611],
 [0.5192722459844176],
 [0.5189362869593361],
 [0.5201268668476384],
 [0.5233343331838134],
 [0.5266123067596168],
 [0.5287225205733285],
 [0.5297858254750678],
 [0.5302667543010386],
 [0.5304397725488187],
 [0.5302099924289121],
 [0.5292883502925644],
 [0.5277065979098441],
 [0.5250410876365905],
 [0.5200417274715174],
 [0.5132986535727021],
 [0.5064448585041565],
 [0.5012087318454366],
 [0.4987547608747972],
 [0.4993123913258908],
 [0.5021715350378145],
 [0.5075651824577254],
 [0.5150086469601562],
 [0.5219507955469299],
 [0.5261273008771106],
 [0.5269353344200389],
 [0.5256080396456136],
 [0.5241887852518122],
 [0.523528570119169],
 [0.524108642608848],
 [0.52694679616542],
 [0.5321146006823577],
 [0.5385921009199703],
 [0.5445840406663216],
 [0.5482635721391217],
 [0.548943450628586],
 [0.5481355756554676],
 [0.5469691724490546],
 [0.5461947019907601],
 [0.5465751688448742],
 [0.5484068524263787],
 [0.551374407425115],
 [0.5547458977040847],
 [0.557907763671875],
 [0.5606737752398997],
 [0.5624835290027648],
 [0.5637600180690191],
 [0.5654643487800319],
 [0.5683512267429828],
 [0.5725600224651345],
 [0.5775414165893896],
 [0.5823171499787962],
 [0.5855331107044575],
 [0.5858038745512131],
 [0.583162676555752],
 [0.5787178468187489],
 [0.5740557561048615],
 [0.5706291339766463],
 [0.5691307594623913],
 [0.5688989158541837],
 [0.5692123510287094],
 [0.56962935497155],
 [0.5687406604244842],
 [0.5655879806211266],
 [0.560468126115177],
 [0.5548827548404363],
 [0.5506337554025794],
 [0.5481648319929138],
 [0.5469153177323844],
 [0.5473666881086349],
 [0.5500188203498739],
 [0.5546775067651416],
 [0.560309669751591],
 [0.5654450383029921],
 [0.569124286019458],
 [0.571886206068935],
 [0.5731449000377911],
 [0.572413502107205],
 [0.5703253596604823],
 [0.5678502897169928],
 [0.5657643377681214],
 [0.5643906645636559],
 [0.5636115608486143],
 [0.5629482339803369],
 [0.5615160044214582],
 [0.5592753043994433],
 [0.5569849479974414],
 [0.5557326381751768],
 [0.5564738748005738],
 [0.5595793353312931],
 [0.5643906875620105],
 [0.569018685822208],
 [0.5720049529892571],
 [0.5734138033718622],
 [0.5741521069967793],
 [0.5752942226099298],
 [0.5775568331046346],
 [0.5809236833769668],
 [0.5844451404173242],
 [0.5875808370743485],
 [0.5901734765426675],
 [0.5908967217471314],
 [0.5888300382576039],
 [0.5843727256687483],
 [0.5791696784379983],
 [0.5750488761817107],
 [0.5721559077399081],
 [0.570741218022124],
 [0.5718699154116493],
 [0.5749761463929731],
 [0.5786521375473277],
 [0.5814432332613889],
 [0.5824798925113561],
 [0.5819466447224101],
 [0.5810327609663308],
 [0.5794271446015262],
 [0.5780733413554787],
 [0.5791703922198544],
 [0.5839364362140721],
 [0.5916566458761866],
 [0.600056501865453],
 [0.607000406676573],
 [0.6122848301586726],
 [0.6139502956373791],
 [0.611001186910653],
 [0.6045686604087961],
 [0.596919123512637],
 [0.5904694785686486],
 [0.5868123249033526],
 [0.5857514008637887],
 [0.5856936087192358],
 [0.5861736535819815],
 [0.5856829393769575],
 [0.5828481999326685],
 [0.5776122194100458],
 [0.5713738895284907],
 [0.5660876035891012],
 [0.5623306997844647],
 [0.5583207489363277],
 [0.5537552540108271],
 [0.5497096813952354],
 [0.5471406261037582],
 [0.5461189796510904],
 [0.545750926451378],
 [0.5447867687425937],
 [0.5429329254143328],
 [0.541960977851016],
 [0.5421665171974486],
 [0.5418315295436283],
 [0.539359045619357],
 [0.534461266318853],
 [0.5282844814139431],
 [0.522470781455839],
 [0.517375782748185],
 [0.5132426497921413],
 [0.5114046696473886],
 [0.5124889370120511],
 [0.5158905676643555],
 [0.519878742033915],
 [0.522303025531581],
 [0.5218999656378628],
 [0.5194416232268811],
 [0.514667496534455],
 [0.5080301020131435],
 [0.5010739902159238],
 [0.49516662479662893],
 [0.49082065502578437],
 [0.48761646506501294],
 [0.484725],
 [0.4817217160032171],
 [0.47810455359515447],
 [0.4734112477387075],
 [0.46772851661927656],
 [0.4617879383241291],
 [0.4567060220293728],
 [0.45336847369453614],
 [0.451464449910793],
 [0.4497431068450214],
 [0.4479051093167798],
 [0.4450846413121916],
 [0.440439614598061],
 [0.4337567965255771],
 [0.42561358057478654],
 [0.41709639963983425],
 [0.40907846216440247],
 [0.40164107613332267],
 [0.39519614181936874],
 [0.39054836536721627],
 [0.38823561996036104],
 [0.3882091296454857],
 [0.3898835171165262],
 [0.3925567154584343],
 [0.39610722531121034],
 [0.40028118626946146],
 [0.40450182120407385],
 [0.4085977494341827],
 [0.4125741843692571],
 [0.416452652466059],
 [0.42021792084477705],
 [0.42387213356433373],
 [0.4273606904689405],
 [0.4294002329877379],
 [0.4293797294257575],
 [0.42788995912525707],
 [0.42599540971100014],
 [0.4246856696765368],
 [0.4245165121200585],
 [0.4254406696298274],
 [0.4269051456710331],
 [0.4283514802355232],
 [0.4293380135166338],
 [0.4297700906452683],
 [0.4300112304112266],
 [0.43074624999092537],
 [0.4325963219904885],
 [0.43548738737594966],
 [0.43883773428535067],
 [0.44297353915274834],
 [0.44747028478515816],
 [0.451500873021234],
 [0.4543881892061281],
 [0.45586329756656163],
 [0.4560292674861076],
 [0.455045013356416],
 [0.4534578604905331],
 [0.4521364567402988],
 [0.4510716698058002],
 [0.44985302324240406],
 [0.4481075421686904],
 [0.4457317816414383],
 [0.4429170376976655],
 [0.43990028508962653],
 [0.43590489545874456],
 [0.43135112121167596],
 [0.4283102920709247],
 [0.4285520297639102],
 [0.432462929467874],
 [0.43894077545399374],
 [0.4462642909307082],
 [0.4537692059534712],
 [0.46127396922810315],
 [0.46739316167696776],
 [0.47081803491549407],
 [0.4712338139557211],
 [0.46954330155327323],
 [0.46740253318355773],
 [0.46606848264719164],
 [0.46492816855075986],
 [0.46317944966495395],
 [0.46146400075989175],
 [0.46081701059086644],
 [0.4618865355207195],
 [0.46458244362054685],
 [0.4681545362707688],
 [0.4716999835571973],
 [0.47537741886241924],
 [0.47979702634060545],
 [0.4834812374099884],
 [0.48453285385295997],
 [0.48209260560339656],
 [0.47682505776488754],
 [0.47043286685986685],
 [0.4642056332796168],
 [0.45802599445286235],
 [0.4526821981791628],
 [0.4494472230091599],
 [0.4488706275085364],
 [0.45030605528065354],
 [0.4521436557729894],
 [0.45274742086737163],
 [0.45199651142277353],
 [0.45007337819439186],
 [0.44643872190848866],
 [0.44174457758550056],
 [0.437029674928842],
 [0.43306954910840656],
 [0.43008136026050275],
 [0.42778342170422223],
 [0.42565548547243603],
 [0.4220296011496883],
 [0.41595690719982215],
 [0.40825224575402874],
 [0.40063282545426954],
 [0.3949252387524502],
 [0.39237926489396113],
 [0.3930884585855883],
 [0.3960615364265592],
 [0.401492186770307],
 [0.4079822894198771],
 [0.4131493538913086],
 [0.4155266217998467],
 [0.4153521436959229],
 [0.414238916849728],
 [0.413726083984375],
 [0.4133459851700061],
 [0.41289427806923534],
 [0.41397053243977044],
 [0.418023892957897],
 [0.42510637323294126],
 [0.43365492394521665],
 [0.4413022751074622],
 [0.4467068708357729],
 [0.4497369303768277],
 [0.4490185745545213],
 [0.4451297472731783],
 [0.43999468809464837],
 [0.4357647768187899],
 [0.4339401862858688],
 [0.4347323434008744],
 [0.43671732937710955],
 [0.43865925060389455],
 [0.43982897512310015],
 [0.43860519543053655],
 [0.43408617712672304],
 [0.42692532804360844],
 [0.4191216590177258],
 [0.41276513630978173],
 [0.40802505324926047],
 [0.4053623430674903],
 [0.40546941877469317],
 [0.4071083767073107],
 [0.408332693095221],
 [0.40749092764640227],
 [0.40388573291276164],
 [0.39808816943712827],
 [0.39186250196962513],
 [0.38719161001471986],
 [0.38522132740003506],
 [0.38598247924394186],
 [0.3884567831530223],
 [0.390998604507784],
 [0.392113443495888],
 [0.391593153892903],
 [0.3914692025269595],
 [0.3935195893613292],
 [0.3979811783104853],
 [0.4041461247752398],
 [0.4108312179186712],
 [0.416853657388228],
 [0.4215133547179868],
 [0.4250806006057156],
 [0.42844134280591223],
 [0.4317259303516026],
 [0.4354222113872473],
 [0.4399072286324239],
 [0.4450076952703485],
 [0.45000475435075027],
 [0.4540830217071157],
 [0.4572133238023473],
 [0.4603122878277328],
 [0.46356881630265895],
 [0.4667529569398437],
 [0.4696341340087773],
 [0.4721752201171687],
 [0.47455802913886924],
 [0.4770402302882666],
 [0.47959653952855047],
 [0.48113312210116965],
 [0.48153016451296116],
 [0.48211737440427804],
 [0.48419271688830656],
 [0.48814234420041497],
 [0.4932402547938401],
 [0.4981276818817345],
 [0.5017945399522643],
 [0.5030742909482165],
 [0.5011391220731543],
 [0.49640128369068903],
 [0.4903034434366233],
 [0.4848116729270746],
 [0.4816250944776906],
 [0.4811021878339603],
 [0.4817358182088732],
 [0.4832161751872419],
 [0.4846391571448248],
 [0.484671888244605],
 [0.482742845165178],
 [0.47946148777801717],
 [0.4762650176010386],
 [0.47429252406313543],
 [0.47384991971629875],
 [0.4762314144862431],
 [0.48114876062903805],
 [0.48698230813252313],
 [0.49174997795712094],
 [0.49391622542084074],
 [0.49304099372847227],
 [0.4902523823699218],
 [0.4868285814003869],
 [0.4832484496542298],
 [0.4812694453602323],
 [0.48229749708710856],
 [0.4862933067486088],
 [0.4917268223282102],
 [0.49657988032340744],
 [0.5003485560757963],
 [0.5042844371528119],
 [0.5080216577153585],
 [0.5103865244196767],
 [0.5106785081127234],
 [0.509222242542397],
 [0.5072166574505266],
 [0.5058812460486367],
 [0.5049375718336656],
 [0.5027095197740519],
 [0.49963525740782877],
 [0.4975102871435077],
 [0.4977531108627907],
 [0.5005246694566698],
 [0.5047166393278936],
 [0.5088085858597832],
 [0.5123974403135193],
 [0.5155149761777937],
 [0.5170373488496202],
 [0.5159455525907701],
 [0.5122812866818396],
 [0.5073079624261799],
 [0.5028770835501934]]